### ISSUE TITLE
Add speaker for beta? If so which model?

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/PhysicalDesign#19]

**Comment by hobodrifterdavid** [comment]
CUI make small speakers, you can get them on digikey. CLS0401MAE should work fine I guess.
Maybe consider a small board that plays audio clips, like: https://www.adafruit.com/product/2341
You'll need a small amplifier too. This is good for prototyping at least, as playing audio can be a bit of a headache on an mcu (need to set up sd card access, file system, buffers, DMA, DAC etc.).

**Comment by inceptionev** [comment]
FYI, if we keep the same display as alpha, there is a pair of speakers on the display that the RPi can access natively through HDMI.  (Tested and this works)

**Comment by neelfirst** [comment]
Closing, since integrated speakers work.
