### ISSUE TITLE
Spec out sw dev care package

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/PhysicalDesign#30]
Create with part numbers and links a package to essential kit a developer needs to move forward with testing against hardware.

Bare essential dev kit
- nucleo-L452RE
- raspi 3b+
- touchscreen
- hdmi cable
- uUSB2 cable x3
- jumpers for UART

Possibly a sensors package?
- 3x MPXV5000
- some 2.5mm tubing
- STEP files for venturi tubes
- instructions for wiring

**Comment by neelfirst** [comment]
Linux SBC: https://www.mouser.com/ProductDetail/Raspberry-Pi/RPI4-MODBP-2GB-BULK
uC Module: https://www.mouser.com/ProductDetail/STMicroelectronics/NUCLEO-L452RE
7" touchscreen: https://www.aliexpress.com/item/4000747984746.html
HDMI-uHDMI cable: https://www.amazon.com/Rankie-Micro-Supports-Ethernet-Return/dp/B00Z07JYLE/
micro USB cable: https://www.amazon.com/dp/B07JBN6C5C/
jumper wires: https://www.amazon.com/GenBasic-Piece-Female-Jumper-Wires/dp/B01L5ULRUA/

**Comment by neelfirst** [comment]
Reference to other components. 

Warning: this BOM is live - https://docs.google.com/spreadsheets/d/1mW5Jr8qKsH8XmUAp5w34JR3UQW4Njy3H/edit#gid=2003192236

**Comment by martukas** [comment]
Where are the assembly instructions for this?
