### ISSUE TITLE
evaluate need for RH sensor in humidifier

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/PhysicalDesign#7]
Can we get away without one and just do open loop control on the humidifier?

or do we need to target a specific RH?

What is the tolerance on the RH?

Possible sensor: https://www.sparkfun.com/products/9569

**Comment by esc-works** [comment]
Had a discussion with Dr. Hara last night which led me to believe that no we did not. Basically he said its an on-off component and they don't try to control humidity. However, we may need this as part of flow sensing, if the humidity appreciably changes the exhale gas density and thus measured flow rate.

**Comment by neelfirst** [comment]
We can create a separate ticket for including RH sensing as part of flow.
