### ISSUE TITLE
Finalize flow measurement solution

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/PhysicalDesign#9]
The flow sensor was originally a pneumotachograph. However, the signal/noise ratio was too high and a venturi was selected as the next option. The venturi was 3D printed with a 0.5 in D and a 0.157 in throat. The venturi calculation spreadsheet is [visible here](https://docs.google.com/spreadsheets/d/1G9Kb-ImlluK8MOx-ce2rlHUBnTOtAFQvKjjs1bEhlpM/edit?usp=sharing). The major problem with venturi is concern over the results in one test, that may be more systemic. 
These results came from one test that @inceptionev ran where we were not able to distinguish the inflow and outflow on exhale. In the plot below, the Orange is the inflow and the purple is the outflow dP. The blue trace is the command pressure and orange trace is measured pressure.
![image (11)](https://user-images.githubusercontent.com/62855852/79355047-09cf7e00-7ef2-11ea-97f1-2683f3748de4.png)
When the solenoid opens, the lungs are deflating (observation) but the plot would indicate that more inflow than exflow means the lungs are deflating. We should plan another test to explore this phenomenon since the spreadsheet indicates what we tested is close to optimized.

**Comment by esc-works** [comment]
Flow sensor specification (note this is the physical interface, assuming the pressure sensor @Edwin Chiu has selected).

- Reading range: 0-80 lpm (@John Batteh whats the largest flow we're seeing on the inflow side?)
- Signal strength: differential pressure range must be between 0-4 kPa
- Pressure loss: no more than 0.1 kPa at 60 liters per minute
- Manufacturing: Should be manufacture-able from injection molded parts (can be two piece). Can be 3d printed for development. Can include machined/stamped parts.
- Pressure sensor can mount to flow instrument but the baseline uses an NXP dP sensor mounted to the PCB with tubing.
- Must interface with 2.5 mm ID tubing (current flow sensor)
- The error/accuracy must be sufficient that during exhale, when the fan is driving flow through both ports, the signal between inhale flow rate and exhale flow rate is distinguishable.
- Response time must be on the order of 50 ms

**Comment by esc-works** [comment]
On suggestion from RED team, may consider these
[DataSheet_PMF4000_MassAirFlow_RevE_C1.pdf](https://github.com/RespiraWorks/PhysicalDesign/files/4511991/DataSheet_PMF4000_MassAirFlow_RevE_C1.pdf)

Also, this link had math for the venturi design: https://docs.google.com/spreadsheets/d/1G9Kb-ImlluK8MOx-ce2rlHUBnTOtAFQvKjjs1bEhlpM/edit#gid=963553579

**Comment by esc-works** [comment]
Also, thought is that the issue with the venturi above related to leakage rather than any issue with the sensor

**Comment by neelfirst** [comment]
@esc-works Is this actually done?

**Comment by esc-works** [comment]
I think we're getting close. It seems like for alpha/beta we'll go with a venturi design. Roughly a 20 degree entrance and 10 degree exhale, with a 4.8mm throat. Its tough because this is almost no resolution around 1 lpm. But it kind of works. We need to characterize it. This is the go forward path until we learn something else

**Comment by neelfirst** [comment]
Let's keep this open then to track the characterization effort of the leading solution. Thanks!

**Comment by neelfirst** [comment]
Merging #3 into this ticket.

**Comment by neelfirst** [comment]
Can we get a condensed summary of testing for this ticket. If the Venturi design as specified above is no longer deemed the best approach why is this and what is the new approach. Thanks

**Comment by neelfirst** [comment]
@esc-works i can haz data

**Comment by esc-works** [comment]
I think this is still the go forward solution as nothing else we've identified has been better. We've tested and will continue to refine the accuracy. It works well with the cheap pressure sensors. We'll find a way to manufacture it. I think we close this ticket as it shouldn't be actively worked on until we learn something else.

**Comment by jlebar** [comment]
Some traces of pressure/flow/etc are available at https://github.com/RespiraWorks/VentilatorSoftware/tree/master/sample-data
